[tox]
envlist = py310, py310-full
isolated_build = True

[testenv]
deps =
    -r requirements/dev.txt
    -r requirements/base.txt
commands =
    pytest -q

[testenv:py310-full]
deps =
    -r requirements/dev.txt
    -r requirements/full.txt
commands =
    pytest -q